bukutamu/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BukutamuCRUDController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('bukutamus', BukutamuCRUDController::class);

Route::get('/', [BukutamuCRUDController::class, 'index']);

bukutamu/app/Models/Bukutamu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bukutamu extends Model
{
    use HasFactory;

    protected $primaryKey = 'nomor';
}

bukutamu/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

bukutamu/app/Http/Controllers/BukutamuCRUDController.php
<?php
namespace App\Http\Controllers;
use App\Models\Bukutamu;
use Illuminate\Http\Request;

class bukutamuCRUDController extends Controller
{

//  Display a listing of the resource.

//  @return \Illuminate\Http\Response

    public function index()
    {
        $data['bukutamus'] = Bukutamu::orderBy('nomor','asc')->paginate(5);
        return view('bukutamus.index', $data);
    }

//  Show the form for creating a new resource.

//  @return \Illuminate\Http\Response

    public function create()
    {
        return view('bukutamus.create');
    }

// Store a newly created resource in storage.

// @param  \Illuminate\Http\Request  $request
// @return \Illuminate\Http\Response

    public function store(Request $request)
    {
        $request->validate([
        'nama' => 'required',
        'email' => 'required',
        'waktu' => 'required',
        'komentar' => 'required'
        ]);
        $bukutamu = new Bukutamu;
        $bukutamu->nama = $request->nama;
        $bukutamu->email = $request->email;
        $bukutamu->waktu = $request->waktu;
        $bukutamu->komentar = $request->komentar;
        $bukutamu->save();
        return redirect()->route('bukutamus.index')
        ->with('success','Data tamu telah tersimpan.');
    }

// Display the specified resource.

// @param  \App\bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function show(Bukutamu $bukutamu)
    {
        return view('bukutamus.show',compact('bukutamu'));
    } 

// Show the form for editing the specified resource.

// @param  \App\Bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function edit(Bukutamu $bukutamu)
    {
        return view('bukutamus.update',compact('bukutamu'));
    }

// Update the specified resource in storage.

// @param  \Illuminate\Http\Request  $request
// @param  \App\bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function update(Request $request, $nomor)
    {
        $request->validate([
        'nama' => 'required',
        'email' => 'required',
        'komentar' => 'required'
        ]);
        $bukutamu = Bukutamu::find($nomor);
        $bukutamu->nama = $request->nama;
        $bukutamu->email = $request->email;
        $bukutamu->komentar = $request->komentar;
        $bukutamu->save();
        return redirect()->route('bukutamus.index')
        ->with('success','Data tamu telah diubah.');
    }

// Remove the specified resource from storage.

// @param  \App\Bukutamu  $bukutamu
// @return \Illuminate\Http\Response

    public function destroy(Bukutamu $bukutamu)
    {
        $bukutamu->delete();
        return redirect()->route('bukutamus.index')
        ->with('success','Data tamu telah dihapus.');
    }
}

bukutamu/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

bukutamu/resources/views/bukutamus/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buku Tamu - Menambah Tamu</title>

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

</head>
<body>

    @if(session('status'))
        <div class="alert alert-success">{{ session('status') }}</div>
    @endif

    <!-- container -->
    <div class="container">
 
        <div class="page-header">
            <h1>Masukkan Data Tamu</h1>
        </div>

        @php
            date_default_timezone_set("Asia/Jakarta");
        @endphp

        <form action="{{ route('bukutamus.store') }}" method="POST">
            @csrf
            <table class='table table-hover table-responsive table-bordered'>
                <tr>
                    <td>Nama</td>
                    <td><input type='text' name='nama' class='form-control' /></td>
                </tr>
                @error('nama')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Email</td>
                    <td><input type='email' name='email' class='form-control'/></td>
                </tr>
                @error('email')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Waktu</td>
                    <td><input type='datetime' name='waktu' class='form-control' value="{{ date('Y-m-d H:i:s') }}"/></td>
                </tr>
                <tr>
                    <td>Komentar</td>
                    <td><textarea name='komentar' class='form-control'></textarea></td>
                </tr>
                @error('komentar')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td></td>
                    <td>
                        <input type='submit' value='Simpan' class='btn btn-warning' />
                        <a class="btn btn-primary" href="{{ route('bukutamus.index') }}">Kembali ke Buku Tamu</a>
                    </td>
                </tr>
            </table>
        </form>
    
    </div> <!-- end .container -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    
    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

bukutamu/resources/views/bukutamus/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buku Tamu - Data Tamu</title>

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
 
    <!-- custom css -->
    <style>
    .m-r-1em{ margin-right:1em; }
    .m-b-1em{ margin-bottom:1em; }
    .m-l-1em{ margin-left:1em; }
    .mt0{ margin-top:0; }
    </style>
    
</head>
<body>

    <!-- container -->
    <div class="container">
 
        <div class="page-header">
            <h1>Buku Data Tamu</h1>
        </div>

        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                {{ $message }}
            </div>
        @endif

        <a class="btn btn-warning m-b-1em" href="{{ route('bukutamus.create') }}">Masukkan Data Tamu Baru</a>

        <table class="table table-hover table-responsive table-bordered">
            
            <tr>
                <th>Nomor</th>
                <th>Nama</th>
                <th>Email</th>
                <th>Waktu</th>
                <th>Komentar</th>
            </tr>

            @foreach ($bukutamus as $bukutamu)
                <tr>
                    <td>{{ $bukutamu->nomor }}</td>
                    <td>{{ $bukutamu->nama }}</td>
                    <td>{{ $bukutamu->email }}</td>
                    <td>{{ $bukutamu->waktu }}</td>
                    <td>{{ $bukutamu->komentar }}</td>

                    <td>
                        <form action="{{ route('bukutamus.destroy',$bukutamu->nomor) }}" method="Post">
                            <a class="btn btn-warning m-r-1em" href="{{ route('bukutamus.edit',$bukutamu->nomor) }}">Ubah</a>
                            @csrf

                            @method('DELETE')
                                <button type="submit" class="btn btn-danger">Hapus</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
        {!! $bukutamus->links() !!}

    </div> <!-- end .container -->
    
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
 
<!-- Latest compiled and minified Bootstrap JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

bukutamu/resources/views/bukutamus/update.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buku Tamu - Ubah Data Tamu</title>
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

</head>
<body>

    <!-- container -->
    <div class="container">
 
        <div class="page-header">
            <h1>Ubah Data Tamu</h1>
        </div>

        @if(session('status'))
            <div class="alert alert-success">{{ session('status') }}</div>
        @endif

        <form action="{{ route('bukutamus.update',$bukutamu->nomor) }}" method="POST">
            @csrf
            @method('PUT')
            <table class='table table-hover table-responsive table-bordered'>
                <tr>
                    <td>Nama</td>
                    <td><input type='text' name='nama' value="{{ $bukutamu->nama }}" class='form-control' /></td>
                </tr>
                @error('nama')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Email</td>
                    <td><input type='email' name='email' value="{{ $bukutamu->email }}" class='form-control'></input></td>
                </tr>
                @error('email')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td>Komentar</td>
                    <td><textarea name='komentar' class='form-control'>{{ $bukutamu->komentar }}</textarea></td>
                </tr>
                @error('komentar')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror
                <tr>
                    <td></td>
                    <td>
                        <input type='submit' value='Simpan Perubahan' class='btn btn-warning' />
                        <a href="{{ route('bukutamus.index') }}" class='btn btn-primary'>Kembali ke Buku Tamu</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</body>
</html>